### ISSUE TITLE
Error running timer ‘dhall-buffer-type-compute’: (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by reuleaux** [psibi/dhall-mode#20]
I get this error currently
```
Error running timer ‘dhall-buffer-type-compute’: (wrong-type-argument stringp nil)
```
with

```
(setq debug-on-error t)
```
I get to see
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("↳" nil nil)
  dhall-buffer-type()
  dhall-buffer-type-compute()
  apply(dhall-buffer-type-compute nil)
  timer-event-handler([t 23511 2211 494750 nil dhall-buffer-type-compute nil nil 157000])
```
any idea? - don't know if this is related to issue #18 
thanks.

**Comment by purcell** [comment]
Which `dhall` version are you using?

**Comment by reuleaux** [comment]
Steve Purcell <notifications@github.com> writes:

R> Which `dhall` version are you using?



rx@mirabelle ~/work/site $ dhall version
1.18.0
rx@mirabelle ~/work/site $


Thanks,
  -A

**Comment by purcell** [comment]
1fa48e3 addresses the error, but I still need to figure out the cause. I think I might have seen something about `dhall` changing so that it no longer prints out the type of the expression by default -- perhaps that's it?

**Comment by haitlahcen** [comment]
@purcell The annotation is not given before the computed value. Before 1.18, you had 
```
type

value
```
now it's
```
value : type
```

I've made it working by hardcoding ugly code (not very fluent in lisp yet).
```
(defun dhall-buffer-type ()
  "Return the type of the expression in the current buffer."
  (interactive)
  (when (executable-find dhall-command)
    (ansi-color-apply (replace-regexp-in-string "[\n\s]+" " " (shell-command-to-string (concat (concat "cat " buffer-file-name) " | dhall resolve | dhall type"))))))
```

**Comment by purcell** [comment]
Thanks. That method won't work when there's no file backing the current buffer, but I'll see what I can do. Certainly looks like the combination of `dhall resolve` and `dhall type` is the way to go.
