### ISSUE TITLE
Support for freezing and updating import sha

### ISSUE THREAD

**Issue by akshaymankar** [psibi/dhall-mode#21]
This would significantly improve time for typechecking.

**Comment by purcell** [comment]
Can't you just use `M-|` (`shell-command-on-region`) to process the current buffer through "dhall freeze"?

**Comment by akshaymankar** [comment]
That works, thanks!

**Comment by purcell** [comment]
I just pushed some changes to make `dhall-mode` use my new `reformatter` library, and as a nice side-effect of that there is now some built-in handling for freezing (and also linting!): you can either call the `dhall-freeze` and `dhall-lint` commands directly as needed, or you can have them applied whenever you save the buffer by adding code to your startup file.
```
(add-hook 'dhall-mode-hook 'dhall-freeze-on-save-mode)
(add-hook 'dhall-mode-hook 'dhall-lint-on-save-mode)
```
This will be in the next version that MELPA builds.
