### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by macalinao** [psibi/dhall-mode#23]
How do I do this? `dhall format` uses spaces but this plugin uses tabs-- any idea why this is?

**Comment by macalinao** [comment]
Nvm, realized that `whitespace-cleanup` is being run by the reformatter. Fixed it using the following:

```
(setq-mode-local dhall-mode indent-tabs-mode nil)
```

**Comment by purcell** [comment]
Yep, I might actually remove the call to `whitespace-cleanup` from `reformatter.el`, but it's specifically needed for `dhall format` because that command actively produces trailing whitespace.

**Comment by neongreen** [comment]
I've been bitten by this.

**Comment by neongreen** [comment]
What about calling `delete-trailing-whitespace` instead of `whitespace-cleanup`?

**Comment by purcell** [comment]
> What about calling `delete-trailing-whitespace` instead of `whitespace-cleanup`?

Good idea, thanks: done. I also suspect that we should set `indent-tabs-mode` to `nil` in `dhall-mode` anyway.

**Comment by purcell** [comment]
> we should set `indent-tabs-mode` to `nil` in `dhall-mode` anyway.

Also done now
