### ISSUE TITLE
REPL support looks for `dhall-repl` command

### ISSUE THREAD

**Issue by endgame** [psibi/dhall-mode#30]
Unlike the `dhall format` support, a quick scan of the code makes me think that the repl support unconditionally looks for `dhall-repl` instead of trying to run `dhall repl`.

**Comment by psibi** [comment]
Yeah, that's right: https://github.com/psibi/dhall-mode/blob/ef4d33debe224c6ba37e51a29b9dc8b74f20f1c2/dhall-mode.el#L305

I wouldn't be opposed adding a new defcustom like `dhall-repl-arguments` instead.

**Comment by purcell** [comment]
Sorry @psibi, I was pushing a fix for this while you were writing your comment. I think the right thing to do these days is just to use `dhall-command`, ie. "dhall" and run `dhall repl` unconditionally.

**Comment by psibi** [comment]
No worries @purcell :-) Thanks for the fix!
