### ISSUE TITLE
dhall resolve is redundant?

### ISSUE THREAD

**Issue by ndwarshuis** [psibi/dhall-mode#37]
I have a massive dhall configuration that takes almost 30 seconds to "type check" in emacs, but only takes a few seconds to type check when loading into my application.

Upon further investigation, it looks like the command this mode runs is `cat <buffer> | dhall resolve | dhall type`. Why is `resolve` necessary? My understanding of this pipeline is that it will read dhall expression, replace all imports with their dhall expressions, and then get the type of this expression. `dhall type` appears follow imports on its own when evaluating the type, thus skipping the creation of a potentially huge expression.

I did some quick benchmarks on my own data, and (at least in my case) taking out the `resolve` step results in the exact same output with 11.5x speedup:

```
> time cat main.dhall | dhall resolve | dhall type > /tmp/both.out
cat main.dhall  0.00s user 0.00s system 82% cpu 0.003 total
dhall resolve  4.96s user 0.22s system 99% cpu 5.181 total
dhall type > /tmp/both.out  21.89s user 0.47s system 81% cpu 27.423 total

> time cat main.dhall | dhall type > /tmp/type.out
cat main.dhall  0.00s user 0.00s system 82% cpu 0.004 total
dhall type > /tmp/type.out  2.43s user 0.15s system 99% cpu 2.592 total

> diff /tmp/both.out /tmp/type.out
<nothing>

> dhall --version
1.41.2
```

**Comment by purcell** [comment]
Hmm, I can't remember why the `resolve` was in there specifically. I added it in 82e67beff02c6c75312576fc11988ca99eeed70d, but it's possible it would work without. Have you tried modifying the code locally and testing it out?

**Comment by ndwarshuis** [comment]
@purcell yes, I also modified `dhall-buffer-type` and it seems to work without issue (except much faster of course)

**Comment by purcell** [comment]
Cool, I committed that change. Thanks!

**Comment by ndwarshuis** [comment]
thank you :)
