### ISSUE TITLE
option to show Type of file in `header-line`

### ISSUE THREAD

**Issue by sellout** [psibi/dhall-mode#6]
The type of the expression in a file can be captured with a command like
```bash
dhall --plain <<< $file 2>&1 >/dev/null
```
This can be used in `header-line-format` to always display the type at the top of the window.

It should also display a reasonable message when 1. there is an error or 2. the type is too large[†].

(I might do this myself, but wanted to open the issue as a reminder until I get to it.)

[†]: Maybe some day there will be a way to acquire a shorter type without it expanding all the aliases and imports along the way.

**Comment by psibi** [comment]
Wow, this would be an amazing thing to add. I'm not sure when I will get to it, but I'm definitely open for a PR.

**Comment by sellout** [comment]
Sweet. Here’s the first swipe:
```emacs-lisp
(setq header-line-format
  '(:eval (split-string (shell-command-to-string (concat "dhall --plain <<< " buffer-file-name " 2>&1 >/dev/null")) nil t split-string-default-separators)))
```

**Comment by psibi** [comment]
Thanks, this looks good. But as you are aware, that for big types this would be a problematic. Probably not showing anything in that case, would be better. Probably we can do this:
* In case, the type exceeds the available space - don't show anything.

I would be open to PR for either that or anything else which you feel would be better.
